# Based on https://stackoverflow.com/questions/18968979/how-to-make-colorized-message-with-cmake
option(MESSAGE_COLORS "Enable message colors" ON)
function(message)
  if(MESSAGE_COLORS and NOT WIN32)
    string(ASCII 27 Esc)
    set(ColorReset "${Esc}[m")
    set(ColorBold  "${Esc}[1m")
    set(Red         "${Esc}[31m")
    set(Green       "${Esc}[32m")
    set(Yellow      "${Esc}[33m")
    set(Blue        "${Esc}[34m")
    set(Magenta     "${Esc}[35m")
    set(Cyan        "${Esc}[36m")
    set(White       "${Esc}[37m")
    set(BoldRed     "${Esc}[1;31m")
    set(BoldGreen   "${Esc}[1;32m")
    set(BoldYellow  "${Esc}[1;33m")
    set(BoldBlue    "${Esc}[1;34m")
    set(BoldMagenta "${Esc}[1;35m")
    set(BoldCyan    "${Esc}[1;36m")
    set(BoldWhite   "${Esc}[1;37m")
  endif()
  list(GET ARGV 0 MessageType)
  if(MessageType STREQUAL FATAL_ERROR OR MessageType STREQUAL SEND_ERROR)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${BoldRed}${ARGV}${ColorReset}")
  elseif(MessageType STREQUAL WARNING)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${BoldYellow}${ARGV}${ColorReset}")
  elseif(MessageType STREQUAL AUTHOR_WARNING)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${BoldCyan}${ARGV}${ColorReset}")
  elseif(MessageType STREQUAL STATUS)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${Green}${ARGV}${ColorReset}")
  else()
    string(TOUPPER MSG_COLOR ${MessageType})
    set(COLOR_RED       ${Red})
    set(COLOR_BLUE      ${Blue})
    set(COLOR_GREEN     ${Green})
    set(COLOR_YELLOW    ${Yellow})
    set(COLOR_MAGENTA   ${Magenta})
    set(COLOR_CYAN      ${Cyan})
    set(COLOR_WHITE     ${White})
    set(COLOR_BOLD      ${Bold})
    set(COLOR_BRED      ${BoldRed})
    set(COLOR_BBLUE     ${BoldBlue})
    set(COLOR_BGREEN    ${BoldGreen})
    set(COLOR_BYELLOW   ${BoldYellow})
    set(COLOR_BMAGENTA  ${BoldMagenta})
    set(COLOR_BCYAN     ${BoldCyan})
    set(COLOR_BWHITE    ${BoldWhite})
    set(COLOR_LIST RED BLUE GREEN YELLOW MAGENTA CYAN WHITE BOLD BRED BBLUE BGREEN BYELLOW BMAGENTA BCYAN BWHITE)
    if(MSG_COLOR IN_LIST COLOR_LIST)
      _message("${COLOR_${MSG_COLOR}}${ARGV}${ColourReset}")
    else()
     _message("${ARGV}")
    endif()
  endif()
endfunction()
